FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY papyrus-ingestor/target/papyrus-ingestor-0.1.0-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", \
  "-XX:+UseContainerSupport", \
  "-XX:MaxRAMPercentage=75.0", \
  "-jar", "app.jar"]
